### ISSUE TITLE
twitchtv.py doesn't work

### ISSUE THREAD

**Issue by dziban303** [dferrante/pywx#21]
```python traceback
root@DZIBOX:/mnt/e/wxbot/newpywx/pywx$ python pywx.py local_config.py
Traceback (most recent call last):
  File "pywx.py", line 9, in <module>
    from modules import *
  File "/mnt/e/wxbot/newpywx/pywx/modules/twitchtv.py", line 6, in <module>
    from twitch import TwitchClient
ImportError: cannot import name TwitchClient```

Not sure what TwitchClient is. It's not a python package according to pip. Also, config file apparently should have the api client and secret but it hasn't been updated.

**Comment by dziban303** [comment]
Something fucky with my python install. Works on another computer. Still, not sure what it's supposed to do.
